### ISSUE TITLE
About the installation of this module

### ISSUE THREAD

**Issue by Wzq740930** [chazi152/Remy_love_mod#2]
I'm sorry to disturb you. I tried many module loaders, but I couldn't use this module. I kept showing an error, which bothered me. I want to ask the correct module loader. Thank you.

**Comment by chazi152** [comment]
Hello, I'm sorry to hear that you are unable to play this mod normally. Actually, because I am a Chinese author, this mod only has a Chinese adaptation version, and the string replacement in the boot file is also a search for the Chinese version of the Dol entry. Other language versions of Dol cannot load this mod
